django_crud-master/django_crud-master/apps/urls.py
from django.urls import include, path
from django.contrib import admin

from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books_cbv.urls', namespace='books_cbv')),

]

django_crud-master/django_crud-master/books_cbv/urls.py
from django.urls import path

from . import views

app_name = 'books_cbv'

urlpatterns = [
  path('', views.BookList.as_view(), name='book_list'),
  path('new', views.BookCreate.as_view(), name='book_new'),
  path('edit/<int:pk>', views.BookUpdate.as_view(), name='book_edit'),
  path('delete/<int:pk>', views.BookDelete.as_view(), name='book_delete'),
]

django_crud-master/django_crud-master/books_cbv/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()
    email = models.EmailField(max_length=200)
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

django_crud-master/django_crud-master/theme/models.py
from django.db import models

# Create your models here.

django_crud-master/django_crud-master/apps/views.py
from django.shortcuts import render

django_crud-master/django_crud-master/books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from books_cbv.models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

django_crud-master/django_crud-master/theme/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

django_crud-master/django_crud-master/books_cbv/templates/books_cbv/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

django_crud-master/django_crud-master/books_cbv/templates/books_cbv/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books Store</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

django_crud-master/django_crud-master/books_cbv/templates/books_cbv/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a></h2>




    <div class="container">
<div class="card">
          <!-- Global site tag (gtag.js) - Google Analytics -->
          <div class="card-header"><i class="fa fa-fw fa-globe"></i> <strong>Browse User</strong> <a href="{% url 'books_cbv:book_new' %}" class="float-right btn btn-dark btn-sm"><i class="fa fa-fw fa-plus-circle"></i> Add Users</a></div>
</div>
    </div>
          
      <br>
      
          
            <div>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr class="bg-primary text-white">
                                <th>Sr#</th>
                                <th>Name</th>
                                <th>Pages</th>
                                
                                <th class="text-center">Edit</th>
                                <th class="text-center">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                                {% for book in object_list %}
                            <tr>
                                    <td>{{ book.id }}</td>
                                    <td>{{ book.name }}</td>
                                    <td> ({{ book.pages }} Pages)</td>
                                    <td align="center"><a href="{% url 'books_cbv:book_edit' book.id %}"  class="text-primary"><i class="fa fa-fw fa-edit"></i>edit</a></td>
                                    <td align="center"><a href="{% url 'books_cbv:book_delete' book.id %}" class="text-danger"><i class="fa fa-fw fa-trash"></i>delete</a></td>   
    
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!--/.col-sm-12-->
                
            </div>



{% endblock %}

django_crud-master/django_crud-master/theme/templates/base.html
{% load static %}

<html>
<head>
    <title></title>
    <style>
            input[type=text], input[type=email], select {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
            }
            input[type=number] {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: #4CAF50;
              color: white;
              padding: 14px 20px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: #45a049;
            }
            
           
            </style>
    <link rel="shortcut icon" href="https://demo.learncodeweb.com/favicon.ico">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
	</head>
    <div id="content">
        <div class="container">
        <div class="row">

<div class="col-md-12">
        {% block content %}
        {% endblock %}
    </div>
   
        </div>
        </div>
        
    </div><!-- content -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    
</body>
</html>

django_crud-master/django_crud-master/theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'books_cbv:book_list' %}">Class Based Views</a><br>

{% endblock %}